// Package score computes scorecards over a submitted consumer verdict,
// sealed ground truth, the delivery ledger and the effector log. The scorer
// never reads a consumer's database or parses its logs: everything it needs
// was generated by the simulator or submitted through sim.consumer.report.
//
// The package is a facade: the rules live in its private domain layer.
package score
