// Package score computes scorecards over a submitted consumer verdict,
// sealed ground truth, the delivery ledger and the effector log. The scorer
// never reads a consumer's database or parses its logs: everything it needs
// was generated by the simulator or submitted through sim.consumer.report.
package score

import (
	"encoding/json"
	"fmt"

	"github.com/ghassan-ai-projects/streams-simulator/internal/model"
	"github.com/ghassan-ai-projects/streams-simulator/internal/run"
)

// scoringBundleVersion names the online/offline scoring bundle. Both paths
// MUST produce identical results for every metric they share; the bundle
// version makes that contract machine-checkable on the scorecard.
const scoringBundleVersion = "scorecard-bundle-v0.1"

// Scorecard is the per-run scoring output (the only artifact anyone outside
// the project reads, so it is JSON-stable).
type Scorecard struct {
	SchemaVersion string                   `json:"schema_version"`
	Bundle        string                   `json:"bundle"`
	RunID         string                   `json:"run_id"`
	Domain        string                   `json:"domain"`
	ScenarioID    string                   `json:"scenario_id,omitempty"`
	GroundTruth   *model.GroundTruthRecord `json:"ground_truth"`
	Reproducible  bool                     `json:"reproducible"`
	Unblinded     bool                     `json:"unblinded"`
	NegativeClass bool                     `json:"negative_class"`
	Instrument    InstrumentMetrics        `json:"instrument"`
	Consumer      ConsumerMetrics          `json:"consumer"`
	Loop          LoopMetrics              `json:"loop"`
	Judgment      JudgmentMetrics          `json:"judgment"`
	Detail        string                   `json:"detail,omitempty"`
}

// InstrumentMetrics are the simulator grading itself: no consumer involved.
type InstrumentMetrics struct {
	LedgerComplete       bool  `json:"ledger_complete"`
	PerturbationFidelity bool  `json:"perturbation_fidelity"`
	EffectorIdempotency  bool  `json:"effector_idempotency"`
	Emitted              int64 `json:"emitted"`
	Delivered            int64 `json:"delivered"`
	Dropped              int64 `json:"dropped"`
	Duplicated           int64 `json:"duplicated"`
	Mangled              int64 `json:"mangled"`
	Delayed              int64 `json:"delayed"`
}

// ConsumerMetrics are computed from the submitted verdict against sealed
// truth and the ledger.
type ConsumerMetrics struct {
	DuplicateHandling      bool `json:"duplicate_handling"`
	IdentityConflict       bool `json:"identity_conflict"`
	LatenessClassification bool `json:"lateness_classification"`
	DroppedEventDetection  bool `json:"dropped_event_detection"`
	ClockSkewRejection     bool `json:"clock_skew_rejection"`
	EvidenceGrounding      bool `json:"evidence_grounding"`
	ActionFidelity         bool `json:"action_fidelity"`
	InterlockHandling      bool `json:"interlock_handling"`
	AdmissionReported      int  `json:"admission_reported"`
	AdmissionExpected      int  `json:"admission_expected"`
}

// LoopMetrics need actuation; only measurable because the loop closes.
type LoopMetrics struct {
	TimeToResolutionNS  int64   `json:"time_to_resolution_ns,omitempty"`
	Resolved            bool    `json:"resolved"`
	DeadlineAdhered     bool    `json:"deadline_adhered,omitempty"`
	UnnecessaryAction   bool    `json:"unnecessary_action,omitempty"`
	ActionAppropriate   bool    `json:"action_appropriate,omitempty"`
	FalseSuccess        bool    `json:"false_success"`
	FalseSuccessRate    float64 `json:"false_success_rate"`
	SilentNoEffectCalls int     `json:"silent_no_effect_calls"`
	EffectCalls         int     `json:"effect_calls"`
}

// JudgmentMetrics need a model; reported per scenario, never gated in CI.
type JudgmentMetrics struct {
	Detected           bool  `json:"detected"`
	LabelCorrect       bool  `json:"label_correct,omitempty"`
	DetectionLatencyNS int64 `json:"detection_latency_ns,omitempty"`
	Suspicious         bool  `json:"suspicious,omitempty"`
	FalsePositive      bool  `json:"false_positive,omitempty"`
	DetectionCount     int   `json:"detection_count"`
}

// Score evaluates one run against its sealed label.
func Score(r *run.Run, gt *model.GroundTruthRecord) (*Scorecard, error) {
	if r.Verdict() == nil {
		return nil, fmt.Errorf("score: no verdict submitted for run %s", r.ID)
	}
	sc := &Scorecard{
		SchemaVersion: "0.1",
		Bundle:        scoringBundleVersion,
		RunID:         r.ID,
		Domain:        gt.Domain,
		ScenarioID:    gt.ScenarioID,
		GroundTruth:   gt,
		Reproducible:  r.Reproducible(),
		Unblinded:     r.UnblindedStamp(),
		NegativeClass: gt.IsNegativeClass,
	}
	sc.Instrument = instrument(r)
	sc.Consumer = consumer(r, gt)
	sc.Judgment = judgment(r, gt)
	sc.Loop = loop(r, gt)
	return sc, nil
}

func instrument(r *run.Run) InstrumentMetrics {
	ledger := r.Ledger()
	m := InstrumentMetrics{LedgerComplete: true, Emitted: r.World.EmittedCount()}
	seenIDs := map[uint64]bool{}
	seenSeq := map[int64]bool{}
	for _, l := range ledger {
		if l.DeliveryID == 0 || seenIDs[l.DeliveryID] {
			m.LedgerComplete = false
		}
		seenIDs[l.DeliveryID] = true
		seenSeq[l.Seq] = true
		switch l.DeliveryReason {
		case model.DeliveryDroppedByPerturb:
			m.Dropped++
		case model.DeliveryDuplicated:
			m.Duplicated++
		case model.DeliveryMangled:
			m.Mangled++
		case model.DeliveryDelayed:
			m.Delayed++
		}
		if l.Delivered {
			m.Delivered++
		}
	}
	for seq := int64(0); seq < m.Emitted; seq++ {
		if !seenSeq[seq] {
			m.LedgerComplete = false
			break
		}
	}
	// Perturbation fidelity: every perturbation that was applied left a mark
	// in the ledger (and never in the delivered event, which is enforced by
	// construction).
	m.PerturbationFidelity = true
	for _, name := range r.AppliedPerturbations() {
		found := false
		for _, l := range ledger {
			if reasonOf(name) == l.DeliveryReason && l.Delivered != (name == "drop") {
				found = true
				break
			}
		}
		if !found {
			m.PerturbationFidelity = false
		}
	}
	// Effector idempotency: no command_id applied twice.
	seen := map[string]bool{}
	m.EffectorIdempotency = true
	for _, c := range r.World.EffectorCalls() {
		if seen[c.CommandID] {
			m.EffectorIdempotency = false
		}
		seen[c.CommandID] = true
	}
	return m
}

func reasonOf(perturbName string) string {
	switch perturbName {
	case "drop":
		return model.DeliveryDroppedByPerturb
	case "duplicate_burst", "storm", "id_reuse":
		return model.DeliveryDuplicated
	case "out_of_enum", "out_of_range", "unit_mismatch", "oversize", "malformed", "nan_inf":
		return model.DeliveryMangled
	case "delay_tail", "gross_backfill", "producer_flap":
		return model.DeliveryDelayed
	case "clock_skew", "non_monotonic", "time_encoding", "precision_edge", "injection_probe":
		return model.DeliveryRewritten
	case "reorder":
		return model.DeliveryReordered
	}
	return ""
}

func consumer(r *run.Run, gt *model.GroundTruthRecord) ConsumerMetrics {
	v := r.Verdict()
	ledger := r.Ledger()
	m := ConsumerMetrics{}

	admissionBySeq := map[int64][]string{}
	for _, a := range v.Admission {
		admissionBySeq[a.Seq] = append(admissionBySeq[a.Seq], a.Outcome)
		m.AdmissionReported++
	}
	deliveredSeqs := map[int64]bool{}
	for _, l := range ledger {
		if l.Delivered {
			deliveredSeqs[l.Seq] = true
		}
	}

	// Duplicate handling: every injected duplicate reported as duplicate.
	m.DuplicateHandling = true
	m.AdmissionExpected = 0
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDuplicated && l.Delivered {
			if !hasOutcome(admissionBySeq[l.Seq], model.AdmissionDuplicate) {
				m.DuplicateHandling = false
			}
		}
	}
	duplicateSeqs := map[int64]bool{}
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDuplicated && l.Delivered {
			duplicateSeqs[l.Seq] = true
		}
	}
	m.AdmissionExpected = len(duplicateSeqs)
	// Identity conflict is applicable only when the identity-reuse
	// perturbation was actually applied; otherwise it is not a failing gate.
	m.IdentityConflict = true
	if hasPerturb(r, "id_reuse") {
		m.IdentityConflict = false
		for _, outcomes := range admissionBySeq {
			if hasOutcome(outcomes, model.AdmissionConflict) {
				m.IdentityConflict = true
				break
			}
		}
	}
	// Lateness: delayed records reported late.
	m.LatenessClassification = true
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDelayed && l.Delivered {
			if o, ok := admissionBySeq[l.Seq]; !ok || !hasOutcome(o, model.AdmissionLate) {
				m.LatenessClassification = false
			}
		}
	}
	// Dropped-event detection: every drop yields an absence detection or an
	// explicit admission gap.
	drops := 0
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDroppedByPerturb && !l.Delivered {
			drops++
		}
	}
	if drops == 0 {
		m.DroppedEventDetection = true
	} else {
		detectionTimes := map[string][]int64{}
		for _, d := range v.Detections {
			t, err := model.ParseTime(d.DetectedAt)
			if err == nil {
				detectionTimes[d.EntityID] = append(detectionTimes[d.EntityID], t)
			}
		}
		m.DroppedEventDetection = false
		used := map[string]map[int]bool{}
		for _, l := range ledger {
			if l.DeliveryReason != model.DeliveryDroppedByPerturb || l.Delivered {
				continue
			}
			if used[l.EntityID] == nil {
				used[l.EntityID] = map[int]bool{}
			}
			for i, t := range detectionTimes[l.EntityID] {
				if used[l.EntityID][i] {
					continue
				}
				// A detection within 30 minutes of the drop window counts.
				if t >= l.ObservedTimeNS-30*60*1e9 && t <= l.ObservedTimeNS+30*60*1e9 {
					used[l.EntityID][i] = true
					break
				}
			}
		}
		matched := 0
		for _, indices := range used {
			matched += len(indices)
		}
		m.DroppedEventDetection = matched == drops
	}
	// Clock skew: skewed records must be explicitly rejected or classified
	// malformed/out-of-contract when the perturbation is active.
	m.ClockSkewRejection = true
	if hasPerturb(r, "clock_skew") {
		m.ClockSkewRejection = false
		for _, outcomes := range admissionBySeq {
			if hasOutcome(outcomes, model.AdmissionRejected) || hasOutcome(outcomes, model.AdmissionMalformed) || hasOutcome(outcomes, model.AdmissionOutOfContract) {
				m.ClockSkewRejection = true
				break
			}
		}
	}
	// Evidence grounding: every cited seq was actually delivered.
	m.EvidenceGrounding = true
	for _, d := range v.Detections {
		for _, ref := range d.EvidenceRefs {
			var seq int64
			if _, err := fmt.Sscanf(ref, "seq:%d", &seq); err == nil {
				if !deliveredSeqs[seq] {
					m.EvidenceGrounding = false
				}
			}
		}
	}
	// Action fidelity: claimed actions match the effector log, and vice
	// versa.
	m.ActionFidelity = true
	usedActions := map[int]bool{}
	for _, c := range r.World.EffectorCalls() {
		matched := false
		for i, a := range v.Actions {
			if usedActions[i] || a.CommandID != c.CommandID || a.Effector != c.Effector || a.EntityID != c.EntityID {
				continue
			}
			issued, err := model.ParseTime(a.IssuedAt)
			if err != nil || issued < c.AtNS {
				continue
			}
			if c.Accepted && a.OutcomeBelieved == model.BelievedFailed {
				continue
			}
			if !c.Accepted && a.OutcomeBelieved == model.BelievedSucceeded {
				continue
			}
			usedActions[i] = true
			matched = true
			break
		}
		if !matched {
			m.ActionFidelity = false
		}
	}
	if len(usedActions) != len(v.Actions) {
		m.ActionFidelity = false
	}
	// Interlock handling: a refusal is never retried with a new command_id
	// for the same effector/entity.
	m.InterlockHandling = true
	refused := map[string]bool{}
	for _, c := range r.World.EffectorCalls() {
		if c.InterlockRefused {
			refused[c.Effector+"/"+c.EntityID] = true
		}
	}
	for _, c := range r.World.EffectorCalls() {
		if refused[c.Effector+"/"+c.EntityID] && !c.InterlockRefused {
			m.InterlockHandling = false
		}
	}
	return m
}

func judgment(r *run.Run, gt *model.GroundTruthRecord) JudgmentMetrics {
	v := r.Verdict()
	m := JudgmentMetrics{DetectionCount: len(v.Detections)}
	if gt.IsNegativeClass && m.DetectionCount > 0 {
		m.FalsePositive = true
	}
	if gt.FirstObservableTimeNS <= 0 {
		return m
	}
	bestAt := int64(0)
	// The graded detection: first detection on the scenario entity, after
	// first_observable_time.
	for _, d := range v.Detections {
		t, err := model.ParseTime(d.DetectedAt)
		if err != nil {
			continue
		}
		if d.EntityID != gt.EntityID {
			continue
		}
		if t < gt.FirstObservableTimeNS {
			m.Suspicious = true
			continue
		}
		if !m.Detected || t < bestAt {
			m.Detected = true
			bestAt = t
			m.DetectionLatencyNS = t - gt.FirstObservableTimeNS
			m.LabelCorrect = d.Label == gt.Label
		}
	}
	return m
}

func loop(r *run.Run, gt *model.GroundTruthRecord) LoopMetrics {
	v := r.Verdict()
	calls := r.World.EffectorCalls()
	m := LoopMetrics{EffectCalls: len(calls)}
	expected := gt.ExpectedEffector
	for _, c := range calls {
		if c.Mode == "silent_no_effect" {
			m.SilentNoEffectCalls++
		}
		if expected != "" && c.Effector == expected && c.EntityID == gt.EntityID && c.EffectApplied {
			m.ActionAppropriate = true
		}
	}
	// False success: a consumer reporting success under silent_no_effect.
	// The full tuple must match the call — command id, effector, entity and
	// claimed outcome — so a claim for a different effector under the same
	// command id is not counted as a false success (it is caught by action
	// fidelity instead).
	type claimed struct {
		effector string
		entity   string
		outcome  string
	}
	byCommand := map[string]claimed{}
	for _, a := range v.Actions {
		byCommand[a.CommandID] = claimed{effector: a.Effector, entity: a.EntityID, outcome: a.OutcomeBelieved}
	}
	falseSuccess := 0
	for _, c := range calls {
		if c.Mode != "silent_no_effect" {
			continue
		}
		claim, ok := byCommand[c.CommandID]
		if ok && claim.outcome == model.BelievedSucceeded && claim.effector == c.Effector && claim.entity == c.EntityID {
			falseSuccess++
		}
	}
	m.FalseSuccessRate = 0
	if m.SilentNoEffectCalls > 0 {
		m.FalseSuccessRate = float64(falseSuccess) / float64(m.SilentNoEffectCalls)
	}
	m.FalseSuccess = falseSuccess > 0
	if gt.IsNegativeClass && len(calls) > 0 {
		m.UnnecessaryAction = true
	}
	// Resolution: did the primary affected state recover after the action?
	if gt.ExpectedEffector != "" && len(calls) > 0 {
		res, t := resolveTime(r, gt)
		m.Resolved = res
		m.TimeToResolutionNS = t
	}
	if gt.DeadlineNS > 0 {
		m.DeadlineAdhered = false
		for _, c := range calls {
			if c.Effector == expected && c.EntityID == gt.EntityID && c.EffectApplied && c.AtNS <= gt.DeadlineNS {
				m.DeadlineAdhered = true
				break
			}
		}
		m.DeadlineAdhered = m.DeadlineAdhered && !m.FalseSuccess && !m.UnnecessaryAction
	}
	return m
}

// resolveTime scans the world after the first successful expected-effector
// call for the primary affected state to return toward its pre-fault level.
func resolveTime(r *run.Run, gt *model.GroundTruthRecord) (bool, int64) {
	fault := faultFor(r, gt.Label)
	if fault == nil || len(fault.Affects) == 0 {
		return false, 0
	}
	state := fault.Affects[0].State
	// Pre-fault baseline: the state just before onset. The sample at or
	// after the onset may already carry the fault when the onset lands on
	// an emission boundary, so the baseline is the latest sample strictly
	// before it.
	base, ok := historyValueBefore(r, gt.EntityID, state, gt.InjectionTimeNS)
	if !ok {
		return false, 0
	}
	faulted, ok := historyValue(r, gt.EntityID, state, gt.FirstObservableTimeNS+60*1e9)
	if !ok {
		return false, 0
	}
	deviation := base - faulted
	if deviation == 0 {
		return false, 0
	}
	// First successful expected-effector call.
	start := int64(0)
	for _, c := range r.World.EffectorCalls() {
		if c.Effector == gt.ExpectedEffector && c.EffectApplied && (start == 0 || c.AtNS < start) {
			start = c.AtNS
		}
	}
	if start == 0 {
		return false, 0
	}
	// Recovery: the state returned within 50% of the deviation.
	recoverLevel := faulted + 0.5*deviation
	for _, snap := range r.History() {
		if snap.Entity != gt.EntityID || snap.TimeNS < start {
			continue
		}
		v := snap.States[state]
		if (deviation > 0 && v >= recoverLevel) || (deviation < 0 && v <= recoverLevel) {
			return true, snap.TimeNS - start
		}
	}
	return false, 0
}

func hasOutcome(outcomes []string, wanted string) bool {
	for _, outcome := range outcomes {
		if outcome == wanted {
			return true
		}
	}
	return false
}

func hasPerturb(r *run.Run, wanted string) bool {
	for _, name := range r.AppliedPerturbations() {
		if name == wanted {
			return true
		}
	}
	return false
}

func historyValue(r *run.Run, entity, state string, atNS int64) (float64, bool) {
	history := r.History()
	if len(history) == 0 {
		return 0, false
	}
	// Prefer the first sample at/after the requested instant, otherwise the
	// latest sample before it. This is random-access over captured evidence;
	// it never advances the mutable world during scoring.
	var before *float64
	var beforeAt int64
	for _, snap := range history {
		if snap.Entity != entity {
			continue
		}
		value, ok := snap.States[state]
		if !ok {
			continue
		}
		if snap.TimeNS >= atNS {
			return value, true
		}
		if before == nil || snap.TimeNS > beforeAt {
			v := value
			before = &v
			beforeAt = snap.TimeNS
		}
	}
	if before != nil {
		return *before, true
	}
	return 0, false
}

// historyValueBefore returns the latest captured sample strictly before t.
// A pre-onset baseline must not read a sample at or after the onset: when
// the fault lands on an emission boundary, that sample already carries the
// fault and the deviation collapses to zero.
func historyValueBefore(r *run.Run, entity, state string, atNS int64) (float64, bool) {
	history := r.History()
	var best *float64
	var bestAt int64
	for _, snap := range history {
		if snap.Entity != entity {
			continue
		}
		value, ok := snap.States[state]
		if !ok {
			continue
		}
		if snap.TimeNS < atNS && (best == nil || snap.TimeNS > bestAt) {
			v := value
			best = &v
			bestAt = snap.TimeNS
		}
	}
	if best != nil {
		return *best, true
	}
	return 0, false
}

func faultFor(r *run.Run, label string) *model.Fault {
	for i := range r.Domain().Spec.Faults {
		if r.Domain().Spec.Faults[i].ID == label {
			return &r.Domain().Spec.Faults[i]
		}
	}
	return nil
}

// Marshal returns the scorecard as indented JSON.
func (s *Scorecard) Marshal() ([]byte, error) {
	raw, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("score: marshal: %w", err)
	}
	return raw, nil
}
