// Package score computes scorecards over a submitted consumer verdict,
// sealed ground truth, the delivery ledger and the effector log. The scorer
// never reads a consumer's database or parses its logs: everything it needs
// was generated by the simulator or submitted through sim.consumer.report.
package score

import (
	"fmt"

	"github.com/ghassan-ai-projects/streams-simulator/internal/model"
	"github.com/ghassan-ai-projects/streams-simulator/internal/run"
)

// scoringBundleVersion names the online/offline scoring bundle. Both paths
// MUST produce identical results for every metric they share; the bundle
// version makes that contract machine-checkable on the scorecard.
const scoringBundleVersion = "scorecard-bundle-v0.2"

// Scorecard is the per-run scoring output (the only artifact anyone outside
// the project reads, so it is JSON-stable).
type Scorecard struct {
	SchemaVersion string                   `json:"schema_version"`
	Bundle        string                   `json:"bundle"`
	RunID         string                   `json:"run_id"`
	Domain        string                   `json:"domain"`
	ScenarioID    string                   `json:"scenario_id,omitempty"`
	GroundTruth   *model.GroundTruthRecord `json:"ground_truth"`
	Reproducible  bool                     `json:"reproducible"`
	Unblinded     bool                     `json:"unblinded"`
	NegativeClass bool                     `json:"negative_class"`
	Instrument    InstrumentMetrics        `json:"instrument"`
	Consumer      ConsumerMetrics          `json:"consumer"`
	Loop          LoopMetrics              `json:"loop"`
	Judgment      JudgmentMetrics          `json:"judgment"`
	Detail        string                   `json:"detail,omitempty"`
}

// InstrumentMetrics are the simulator grading itself: no consumer involved.
type InstrumentMetrics struct {
	LedgerComplete       bool  `json:"ledger_complete"`
	PerturbationFidelity bool  `json:"perturbation_fidelity"`
	EffectorIdempotency  bool  `json:"effector_idempotency"`
	Emitted              int64 `json:"emitted"`
	Delivered            int64 `json:"delivered"`
	Dropped              int64 `json:"dropped"`
	Duplicated           int64 `json:"duplicated"`
	Mangled              int64 `json:"mangled"`
	Delayed              int64 `json:"delayed"`
}

// ConsumerMetrics are computed from the submitted verdict against sealed
// truth and the ledger.
type ConsumerMetrics struct {
	DuplicateHandling      bool `json:"duplicate_handling"`
	IdentityConflict       bool `json:"identity_conflict"`
	LatenessClassification bool `json:"lateness_classification"`
	DroppedEventDetection  bool `json:"dropped_event_detection"`
	ClockSkewRejection     bool `json:"clock_skew_rejection"`
	EvidenceGrounding      bool `json:"evidence_grounding"`
	ActionFidelity         bool `json:"action_fidelity"`
	InterlockHandling      bool `json:"interlock_handling"`
	AdmissionReported      int  `json:"admission_reported"`
	AdmissionExpected      int  `json:"admission_expected"`
}

// LoopMetrics need actuation; only measurable because the loop closes.
type LoopMetrics struct {
	TimeToResolutionNS  int64   `json:"time_to_resolution_ns,omitempty"`
	Resolved            bool    `json:"resolved"`
	DeadlineAdhered     bool    `json:"deadline_adhered,omitempty"`
	UnnecessaryAction   bool    `json:"unnecessary_action,omitempty"`
	ActionAppropriate   bool    `json:"action_appropriate,omitempty"`
	FalseSuccess        bool    `json:"false_success"`
	FalseSuccessRate    float64 `json:"false_success_rate"`
	SilentNoEffectCalls int     `json:"silent_no_effect_calls"`
	EffectCalls         int     `json:"effect_calls"`
}

// JudgmentMetrics need a model; reported per scenario, never gated in CI.
type JudgmentMetrics struct {
	Detected           bool  `json:"detected"`
	LabelCorrect       bool  `json:"label_correct,omitempty"`
	DetectionLatencyNS int64 `json:"detection_latency_ns,omitempty"`
	Suspicious         bool  `json:"suspicious,omitempty"`
	FalsePositive      bool  `json:"false_positive,omitempty"`
	DetectionCount     int   `json:"detection_count"`
}

// Score evaluates one run against its sealed label.
func Score(r *run.Run, gt *model.GroundTruthRecord) (*Scorecard, error) {
	if r.Verdict() == nil {
		return nil, fmt.Errorf("score: no verdict submitted for run %s", r.ID)
	}
	sc := newScorecard(r.ID, gt)
	sc.Reproducible, sc.Unblinded = r.Reproducible(), r.UnblindedStamp()
	sc.Instrument = instrument(r)
	sc.Consumer = consumer(r, gt)
	sc.Judgment = judgment(r, gt)
	sc.Loop = loop(r, gt)
	return sc, nil
}

func newScorecard(runID string, gt *model.GroundTruthRecord) *Scorecard {
	return &Scorecard{
		SchemaVersion: "0.1", Bundle: scoringBundleVersion,
		RunID: runID, Domain: gt.Domain, ScenarioID: gt.ScenarioID,
		GroundTruth: gt, NegativeClass: gt.IsNegativeClass,
	}
}
