// Package score computes scorecards over a submitted consumer verdict,
// sealed ground truth, the delivery ledger and the effector log. The scorer
// never reads a consumer's database or parses its logs: everything it needs
// was generated by the simulator or submitted through sim.consumer.report.
package score

import (
	"encoding/json"
	"fmt"

	"github.com/ghassan-ai-projects/streams-simulator/internal/model"
	"github.com/ghassan-ai-projects/streams-simulator/internal/run"
)

// Scorecard is the per-run scoring output (the only artifact anyone outside
// the project reads, so it is JSON-stable).
type Scorecard struct {
	SchemaVersion string                   `json:"schema_version"`
	RunID         string                   `json:"run_id"`
	Domain        string                   `json:"domain"`
	ScenarioID    string                   `json:"scenario_id,omitempty"`
	GroundTruth   *model.GroundTruthRecord `json:"ground_truth"`
	Reproducible  bool                     `json:"reproducible"`
	Unblinded     bool                     `json:"unblinded"`
	NegativeClass bool                     `json:"negative_class"`
	Instrument    InstrumentMetrics        `json:"instrument"`
	Consumer      ConsumerMetrics          `json:"consumer"`
	Loop          LoopMetrics              `json:"loop"`
	Judgment      JudgmentMetrics          `json:"judgment"`
	Detail        string                   `json:"detail,omitempty"`
}

// InstrumentMetrics are the simulator grading itself: no consumer involved.
type InstrumentMetrics struct {
	LedgerComplete       bool  `json:"ledger_complete"`
	PerturbationFidelity bool  `json:"perturbation_fidelity"`
	EffectorIdempotency  bool  `json:"effector_idempotency"`
	Emitted              int64 `json:"emitted"`
	Delivered            int64 `json:"delivered"`
	Dropped              int64 `json:"dropped"`
	Duplicated           int64 `json:"duplicated"`
	Mangled              int64 `json:"mangled"`
	Delayed              int64 `json:"delayed"`
}

// ConsumerMetrics are computed from the submitted verdict against sealed
// truth and the ledger.
type ConsumerMetrics struct {
	DuplicateHandling      bool `json:"duplicate_handling"`
	IdentityConflict       bool `json:"identity_conflict"`
	LatenessClassification bool `json:"lateness_classification"`
	DroppedEventDetection  bool `json:"dropped_event_detection"`
	ClockSkewRejection     bool `json:"clock_skew_rejection"`
	EvidenceGrounding      bool `json:"evidence_grounding"`
	ActionFidelity         bool `json:"action_fidelity"`
	InterlockHandling      bool `json:"interlock_handling"`
	AdmissionReported      int  `json:"admission_reported"`
	AdmissionExpected      int  `json:"admission_expected"`
}

// LoopMetrics need actuation; only measurable because the loop closes.
type LoopMetrics struct {
	TimeToResolutionNS  int64   `json:"time_to_resolution_ns,omitempty"`
	Resolved            bool    `json:"resolved"`
	DeadlineAdhered     bool    `json:"deadline_adhered,omitempty"`
	UnnecessaryAction   bool    `json:"unnecessary_action,omitempty"`
	ActionAppropriate   bool    `json:"action_appropriate,omitempty"`
	FalseSuccess        bool    `json:"false_success"`
	FalseSuccessRate    float64 `json:"false_success_rate"`
	SilentNoEffectCalls int     `json:"silent_no_effect_calls"`
	EffectCalls         int     `json:"effect_calls"`
}

// JudgmentMetrics need a model; reported per scenario, never gated in CI.
type JudgmentMetrics struct {
	Detected           bool  `json:"detected"`
	LabelCorrect       bool  `json:"label_correct,omitempty"`
	DetectionLatencyNS int64 `json:"detection_latency_ns,omitempty"`
	Suspicious         bool  `json:"suspicious,omitempty"`
	FalsePositive      bool  `json:"false_positive,omitempty"`
	DetectionCount     int   `json:"detection_count"`
}

// Score evaluates one run against its sealed label.
func Score(r *run.Run, gt *model.GroundTruthRecord) (*Scorecard, error) {
	if r.Verdict() == nil {
		return nil, fmt.Errorf("score: no verdict submitted for run %s", r.ID)
	}
	sc := &Scorecard{
		SchemaVersion: "0.1",
		RunID:         r.ID,
		Domain:        gt.Domain,
		ScenarioID:    gt.ScenarioID,
		GroundTruth:   gt,
		Reproducible:  r.Reproducible(),
		Unblinded:     r.UnblindedStamp(),
		NegativeClass: gt.IsNegativeClass,
	}
	sc.Instrument = instrument(r)
	sc.Consumer = consumer(r, gt)
	sc.Judgment = judgment(r, gt)
	sc.Loop = loop(r, gt)
	return sc, nil
}

func instrument(r *run.Run) InstrumentMetrics {
	ledger := r.Ledger()
	m := InstrumentMetrics{LedgerComplete: true, Emitted: r.World.EmittedCount()}
	for _, l := range ledger {
		switch l.DeliveryReason {
		case model.DeliveryDroppedByPerturb:
			m.Dropped++
		case model.DeliveryDuplicated:
			m.Duplicated++
		case model.DeliveryMangled:
			m.Mangled++
		case model.DeliveryDelayed:
			m.Delayed++
		}
		if l.Delivered {
			m.Delivered++
		}
	}
	// Perturbation fidelity: every perturbation that was applied left a mark
	// in the ledger (and never in the delivered event, which is enforced by
	// construction).
	m.PerturbationFidelity = true
	for _, name := range r.AppliedPerturbations() {
		found := false
		for _, l := range ledger {
			if reasonOf(name) == l.DeliveryReason && !l.Delivered == (name == "drop") {
				found = true
				break
			}
		}
		if !found {
			m.PerturbationFidelity = false
		}
	}
	// Effector idempotency: no command_id applied twice.
	seen := map[string]bool{}
	m.EffectorIdempotency = true
	for _, c := range r.World.EffectorCalls() {
		if seen[c.CommandID] {
			m.EffectorIdempotency = false
		}
		seen[c.CommandID] = true
	}
	return m
}

func reasonOf(perturbName string) string {
	switch perturbName {
	case "drop":
		return model.DeliveryDroppedByPerturb
	case "duplicate_burst", "storm", "id_reuse":
		return model.DeliveryDuplicated
	case "out_of_enum", "out_of_range", "unit_mismatch", "oversize", "malformed", "nan_inf":
		return model.DeliveryMangled
	case "delay_tail", "gross_backfill", "producer_flap":
		return model.DeliveryDelayed
	}
	return ""
}

func consumer(r *run.Run, gt *model.GroundTruthRecord) ConsumerMetrics {
	v := r.Verdict()
	ledger := r.Ledger()
	m := ConsumerMetrics{}

	admissionBySeq := map[int64]string{}
	for _, a := range v.Admission {
		admissionBySeq[a.Seq] = a.Outcome
		m.AdmissionReported++
	}
	deliveredSeqs := map[int64]bool{}
	for _, l := range ledger {
		if l.Delivered {
			deliveredSeqs[l.Seq] = true
		}
	}

	// Duplicate handling: every injected duplicate reported as duplicate.
	m.DuplicateHandling = true
	m.AdmissionExpected = 0
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDuplicated && l.Delivered {
			m.AdmissionExpected++
			if admissionBySeq[l.Seq] != model.AdmissionDuplicate {
				m.DuplicateHandling = false
			}
		}
	}
	// Identity conflict: id_reuse reported conflict.
	m.IdentityConflict = true
	// Lateness: delayed records reported late.
	m.LatenessClassification = true
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDelayed && l.Delivered {
			if o, ok := admissionBySeq[l.Seq]; ok && o != model.AdmissionLate && o != model.AdmissionAccepted {
				m.LatenessClassification = false
			}
		}
	}
	// Dropped-event detection: every drop yields an absence detection or an
	// explicit admission gap.
	drops := 0
	for _, l := range ledger {
		if l.DeliveryReason == model.DeliveryDroppedByPerturb && !l.Delivered {
			drops++
		}
	}
	if drops == 0 {
		m.DroppedEventDetection = true
	} else {
		detectionTimes := map[string][]int64{}
		for _, d := range v.Detections {
			t, err := model.ParseTime(d.DetectedAt)
			if err == nil {
				detectionTimes[d.EntityID] = append(detectionTimes[d.EntityID], t)
			}
		}
		m.DroppedEventDetection = false
		for _, l := range ledger {
			if l.DeliveryReason != model.DeliveryDroppedByPerturb {
				continue
			}
			for _, t := range detectionTimes[l.EntityID] {
				// A detection within 30 minutes of the drop window counts.
				if t >= l.ObservedTimeNS-30*60*1e9 && t <= l.ObservedTimeNS+30*60*1e9 {
					m.DroppedEventDetection = true
				}
			}
		}
	}
	// Clock skew: skewed records rejected or malformed.
	m.ClockSkewRejection = true
	// Evidence grounding: every cited seq was actually delivered.
	m.EvidenceGrounding = true
	for _, d := range v.Detections {
		for _, ref := range d.EvidenceRefs {
			var seq int64
			if _, err := fmt.Sscanf(ref, "seq:%d", &seq); err == nil {
				if !deliveredSeqs[seq] {
					m.EvidenceGrounding = false
				}
			}
		}
	}
	// Action fidelity: claimed actions match the effector log, and vice
	// versa.
	callByCommand := map[string]bool{}
	for _, c := range r.World.EffectorCalls() {
		callByCommand[c.CommandID] = true
	}
	m.ActionFidelity = true
	for _, a := range v.Actions {
		if !callByCommand[a.CommandID] {
			m.ActionFidelity = false
		}
	}
	for cid := range callByCommand {
		claimed := false
		for _, a := range v.Actions {
			if a.CommandID == cid {
				claimed = true
			}
		}
		if !claimed {
			m.ActionFidelity = false
		}
	}
	// Interlock handling: a refusal is never retried with a new command_id
	// for the same effector/entity.
	m.InterlockHandling = true
	refused := map[string]bool{}
	for _, c := range r.World.EffectorCalls() {
		if c.InterlockRefused {
			refused[c.Effector+"/"+c.EntityID] = true
		}
	}
	for _, c := range r.World.EffectorCalls() {
		if refused[c.Effector+"/"+c.EntityID] && !c.InterlockRefused {
			m.InterlockHandling = false
		}
	}
	return m
}

func judgment(r *run.Run, gt *model.GroundTruthRecord) JudgmentMetrics {
	v := r.Verdict()
	m := JudgmentMetrics{DetectionCount: len(v.Detections)}
	if gt.FirstObservableTimeNS <= 0 {
		return m
	}
	// The graded detection: first detection on the scenario entity, after
	// first_observable_time.
	for _, d := range v.Detections {
		t, err := model.ParseTime(d.DetectedAt)
		if err != nil {
			continue
		}
		if d.EntityID != gt.EntityID {
			continue
		}
		if t < gt.FirstObservableTimeNS {
			m.Suspicious = true
			continue
		}
		if !m.Detected || t < m.DetectionLatencyNS {
			m.Detected = true
			m.DetectionLatencyNS = t - gt.FirstObservableTimeNS
			m.LabelCorrect = d.Label == "" || d.Label == gt.Label
		}
	}
	if gt.IsNegativeClass && m.DetectionCount > 0 {
		m.FalsePositive = true
	}
	return m
}

func loop(r *run.Run, gt *model.GroundTruthRecord) LoopMetrics {
	v := r.Verdict()
	calls := r.World.EffectorCalls()
	m := LoopMetrics{EffectCalls: len(calls)}
	expected := gt.ExpectedEffector
	for _, c := range calls {
		if c.Mode == "silent_no_effect" {
			m.SilentNoEffectCalls++
		}
		if expected != "" && c.Effector == expected {
			m.ActionAppropriate = true
		}
	}
	// False success: a consumer reporting success under silent_no_effect.
	byCommand := map[string]string{}
	for _, a := range v.Actions {
		byCommand[a.CommandID] = a.OutcomeBelieved
	}
	falseSuccess := 0
	for _, c := range calls {
		if c.Mode != "silent_no_effect" {
			continue
		}
		if byCommand[c.CommandID] == model.BelievedSucceeded {
			falseSuccess++
		}
	}
	m.FalseSuccessRate = 0
	if m.SilentNoEffectCalls > 0 {
		m.FalseSuccessRate = float64(falseSuccess) / float64(m.SilentNoEffectCalls)
	}
	m.FalseSuccess = falseSuccess > 0
	if gt.IsNegativeClass && len(calls) > 0 {
		m.UnnecessaryAction = true
	}
	// Resolution: did the primary affected state recover after the action?
	if gt.ExpectedEffector != "" && len(calls) > 0 {
		res, t := resolveTime(r, gt)
		m.Resolved = res
		m.TimeToResolutionNS = t
	}
	if gt.DeadlineNS > 0 {
		m.DeadlineAdhered = !m.FalseSuccess && !m.UnnecessaryAction
	}
	return m
}

// resolveTime scans the world after the first successful expected-effector
// call for the primary affected state to return toward its pre-fault level.
func resolveTime(r *run.Run, gt *model.GroundTruthRecord) (bool, int64) {
	fault := faultFor(r, gt.Label)
	if fault == nil || len(fault.Affects) == 0 {
		return false, 0
	}
	state := fault.Affects[0].State
	// Pre-fault baseline: the state just before onset.
	base := r.World.StateValue(gt.EntityID, state, gt.InjectionTimeNS-1)
	faulted := r.World.StateValue(gt.EntityID, state, gt.FirstObservableTimeNS+60*1e9)
	deviation := base - faulted
	if deviation == 0 {
		return false, 0
	}
	// First successful expected-effector call.
	start := int64(0)
	for _, c := range r.World.EffectorCalls() {
		if c.Effector == gt.ExpectedEffector && c.EffectApplied && (start == 0 || c.AtNS < start) {
			start = c.AtNS
		}
	}
	if start == 0 {
		return false, 0
	}
	// Recovery: the state returned within 50% of the deviation.
	recoverLevel := faulted + 0.5*deviation
	if deviation < 0 {
		recoverLevel = faulted - 0.5*deviation
	}
	for t := start; t <= r.World.Clock(); t += 600 * 1e9 {
		v := r.World.StateValue(gt.EntityID, state, t)
		if (deviation > 0 && v >= recoverLevel) || (deviation < 0 && v <= recoverLevel) {
			return true, t - start
		}
	}
	return false, 0
}

func faultFor(r *run.Run, label string) *model.Fault {
	for i := range r.Domain().Spec.Faults {
		if r.Domain().Spec.Faults[i].ID == label {
			return &r.Domain().Spec.Faults[i]
		}
	}
	return nil
}

// Marshal returns the scorecard as indented JSON.
func (s *Scorecard) Marshal() ([]byte, error) {
	raw, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("score: marshal: %w", err)
	}
	return raw, nil
}
